name: workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  
  deploy-test:
    uses: ./.github/workflows/deploy.yaml
    needs: lint
    with:
      environmentType: Test
      resourceGroupName: RG-Bicep-Test
      reviewApiUrl: https://sandbox.contoso.com/reviews
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}
  deploy-production:
    uses: ./.github/workflows/deploy.yaml
    needs: deploy-test
    with:
      environmentType: Production
      resourceGroupName: RG-Bicep-Production
      reviewApiUrl: https://api.contoso.com/reviews
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PRODUCTION }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}